INFO 24-09-2023 10:22:38 autoreload Watching for file changes with StatReloader
INFO 24-09-2023 10:24:21 autoreload C:\Users\ersho\PycharmProjects\gb_django_1\home\home\settings.py changed, reloading.
INFO 24-09-2023 10:27:17 autoreload Watching for file changes with StatReloader
ERROR 24-09-2023 10:27:29 log Internal Server Error: /h2shop/iv/
Traceback (most recent call last):
  File "C:\Users\ersho\PycharmProjects\gb_django_1\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ersho\PycharmProjects\gb_django_1\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ersho\PycharmProjects\gb_django_1\home\home2shopapp\views.py", line 20, in is_visible
    if data['id']:
       ~~~~^^^^^^
TypeError: string indices must be integers, not 'str'
ERROR 24-09-2023 10:27:29 basehttp "GET /h2shop/iv/?id=1&is_visible=0 HTTP/1.1" 500 65965
INFO 24-09-2023 10:30:18 autoreload C:\Users\ersho\PycharmProjects\gb_django_1\home\home2shopapp\views.py changed, reloading.
INFO 24-09-2023 10:30:19 autoreload Watching for file changes with StatReloader
INFO 24-09-2023 10:30:22 basehttp "GET /h2shop/iv/?id=1&is_visible=0 HTTP/1.1" 200 84
INFO 24-09-2023 10:31:14 autoreload C:\Users\ersho\PycharmProjects\gb_django_1\home\home2shopapp\views.py changed, reloading.
INFO 24-09-2023 10:32:12 autoreload Watching for file changes with StatReloader
INFO 24-09-2023 11:07:45 autoreload C:\Users\ersho\PycharmProjects\gb_django_1\home\home2shopapp\views.py changed, reloading.
INFO 24-09-2023 11:07:46 autoreload Watching for file changes with StatReloader
INFO 24-09-2023 11:07:49 basehttp "GET /h2shop/ HTTP/1.1" 200 208
INFO 24-09-2023 11:09:06 autoreload C:\Users\ersho\PycharmProjects\gb_django_1\home\home2shopapp\views.py changed, reloading.
INFO 24-09-2023 11:09:06 autoreload Watching for file changes with StatReloader
INFO 24-09-2023 11:09:07 basehttp "GET /h2shop/ HTTP/1.1" 200 127
INFO 24-09-2023 11:15:14 autoreload C:\Users\ersho\PycharmProjects\gb_django_1\home\home2shopapp\views.py changed, reloading.
INFO 24-09-2023 11:15:14 autoreload Watching for file changes with StatReloader
INFO 24-09-2023 11:17:23 autoreload C:\Users\ersho\PycharmProjects\gb_django_1\home\home2shopapp\views.py changed, reloading.
INFO 24-09-2023 11:17:24 autoreload Watching for file changes with StatReloader
WARNING 24-09-2023 11:17:33 log Not Found: /h2shop/del_product/1&confirm=yes
WARNING 24-09-2023 11:17:33 basehttp "GET /h2shop/del_product/1&confirm=yes HTTP/1.1" 404 4311
WARNING 24-09-2023 11:17:52 log Not Found: /h2shop/del/1&confirm=yes
WARNING 24-09-2023 11:17:52 basehttp "GET /h2shop/del/1&confirm=yes HTTP/1.1" 404 4287
INFO 24-09-2023 11:18:10 basehttp "GET /h2shop/del/1?confirm=yes HTTP/1.1" 200 34
INFO 24-09-2023 11:18:56 autoreload C:\Users\ersho\PycharmProjects\gb_django_1\home\home2shopapp\views.py changed, reloading.
INFO 24-09-2023 11:18:56 autoreload Watching for file changes with StatReloader
INFO 24-09-2023 11:20:25 autoreload C:\Users\ersho\PycharmProjects\gb_django_1\home\home2shopapp\models.py changed, reloading.
INFO 24-09-2023 11:20:26 autoreload Watching for file changes with StatReloader
INFO 24-09-2023 11:25:44 autoreload Watching for file changes with StatReloader
INFO 24-09-2023 11:25:47 basehttp "GET /h2shop/ HTTP/1.1" 200 246
INFO 24-09-2023 11:28:42 autoreload C:\Users\ersho\PycharmProjects\gb_django_1\home\home2shopapp\views.py changed, reloading.
INFO 24-09-2023 11:28:42 autoreload Watching for file changes with StatReloader
INFO 24-09-2023 11:29:45 autoreload C:\Users\ersho\PycharmProjects\gb_django_1\home\home2shopapp\models.py changed, reloading.
INFO 24-09-2023 11:29:45 autoreload Watching for file changes with StatReloader
INFO 24-09-2023 11:29:47 basehttp "GET /h2shop/ HTTP/1.1" 200 258
INFO 24-09-2023 11:30:06 basehttp "GET /h2shop/del/8 HTTP/1.1" 200 67
INFO 24-09-2023 11:30:32 basehttp "GET /h2shop/iv/?id=8&is_visible=1 HTTP/1.1" 200 110
INFO 24-09-2023 11:30:40 basehttp "GET /h2shop/ HTTP/1.1" 200 258
INFO 25-09-2023 09:28:12 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 09:28:13 views Index page accessed
ERROR 25-09-2023 09:28:14 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py", line 12, in index
    return render(request, 'myapp/index.html')
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 25-09-2023 09:28:14 basehttp "GET / HTTP/1.1" 500 136493
INFO 25-09-2023 09:29:24 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home\settings.py changed, reloading.
INFO 25-09-2023 09:29:25 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 09:29:28 views Index page accessed
INFO 25-09-2023 09:29:28 basehttp "GET / HTTP/1.1" 200 2455
INFO 25-09-2023 09:29:38 views Index page accessed
INFO 25-09-2023 09:29:38 basehttp "GET / HTTP/1.1" 200 2455
ERROR 25-09-2023 09:29:39 log Internal Server Error: /lesson1/
Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: myapp/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py", line 90, in lesson1
    return render(request, 'myapp/lesson_1.html')
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: myapp/base.html
ERROR 25-09-2023 09:29:39 basehttp "GET /lesson1/ HTTP/1.1" 500 138316
INFO 25-09-2023 09:29:52 basehttp "GET /lesson1/ HTTP/1.1" 200 3039
INFO 25-09-2023 09:33:48 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\urls.py changed, reloading.
INFO 25-09-2023 09:33:49 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 09:34:56 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 09:34:57 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 09:37:12 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 09:37:14 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 09:37:19 basehttp "GET /lesson1/ HTTP/1.1" 200 2997
INFO 25-09-2023 09:42:58 views Index page accessed
ERROR 25-09-2023 09:42:58 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py", line 13, in index
    return render(request, 'myapp/index.html')
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 6: 'static'. Did you forget to register or load this tag?
ERROR 25-09-2023 09:42:58 basehttp "GET / HTTP/1.1" 500 177969
INFO 25-09-2023 09:43:38 views Index page accessed
INFO 25-09-2023 09:43:38 basehttp "GET / HTTP/1.1" 200 2770
INFO 25-09-2023 09:43:39 basehttp "GET /static/myapp/ico/site.webmanifest HTTP/1.1" 200 263
INFO 25-09-2023 09:43:39 basehttp "GET /static/myapp/ico/favicon-32x32.png HTTP/1.1" 200 687
INFO 25-09-2023 09:44:47 views Index page accessed
INFO 25-09-2023 09:44:47 basehttp "GET / HTTP/1.1" 200 2770
INFO 25-09-2023 09:44:48 views Index page accessed
INFO 25-09-2023 09:44:48 basehttp "GET / HTTP/1.1" 200 2770
INFO 25-09-2023 09:44:55 views Index page accessed
INFO 25-09-2023 09:44:55 basehttp "GET / HTTP/1.1" 200 2770
INFO 25-09-2023 09:45:07 views Index page accessed
INFO 25-09-2023 09:45:07 basehttp "GET / HTTP/1.1" 200 2770
INFO 25-09-2023 09:45:08 views Index page accessed
INFO 25-09-2023 09:45:08 basehttp "GET / HTTP/1.1" 200 2776
ERROR 25-09-2023 09:45:11 log Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 5: 'block'. Looking for one of: endblock.
ERROR 25-09-2023 09:45:11 basehttp "GET /about/ HTTP/1.1" 500 164765
INFO 25-09-2023 09:45:35 basehttp "GET /about/ HTTP/1.1" 200 3279
INFO 25-09-2023 09:45:53 basehttp "GET /about/ HTTP/1.1" 200 3274
INFO 25-09-2023 09:47:35 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 09:47:37 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 09:48:11 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\urls.py changed, reloading.
INFO 25-09-2023 09:48:12 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 09:48:13 basehttp "GET / HTTP/1.1" 200 2793
INFO 25-09-2023 09:53:49 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 09:53:50 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:21:17 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 10:21:18 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:23:33 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 10:23:34 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:23:57 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 10:23:58 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:24:21 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 10:24:22 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:24:52 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 10:24:53 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:26:11 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 10:26:12 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:27:35 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 10:27:36 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:27:44 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 10:27:45 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:30:52 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 10:30:53 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:34:04 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 10:34:05 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:38:36 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 10:38:37 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:40:58 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\urls.py changed, reloading.
INFO 25-09-2023 10:40:59 autoreload Watching for file changes with StatReloader
ERROR 25-09-2023 10:41:18 log Internal Server Error: /l3/bin/10
Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: index_wo_templates() got an unexpected keyword argument 'n'
ERROR 25-09-2023 10:41:18 basehttp "GET /l3/bin/10 HTTP/1.1" 500 71006
INFO 25-09-2023 10:41:54 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 10:41:55 autoreload Watching for file changes with StatReloader
ERROR 25-09-2023 10:41:56 log Internal Server Error: /l3/bin/10
Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: index_wo_templates() got an unexpected keyword argument 'n'
ERROR 25-09-2023 10:41:56 basehttp "GET /l3/bin/10 HTTP/1.1" 500 71143
ERROR 25-09-2023 10:41:57 log Internal Server Error: /l3/bin/10
Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: index_wo_templates() got an unexpected keyword argument 'n'
ERROR 25-09-2023 10:41:57 basehttp "GET /l3/bin/10 HTTP/1.1" 500 71143
INFO 25-09-2023 10:42:34 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 10:42:35 autoreload Watching for file changes with StatReloader
ERROR 25-09-2023 10:42:36 log Internal Server Error: /l3/bin/10
Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: index_wo_templates() got an unexpected keyword argument 'n'
ERROR 25-09-2023 10:42:36 basehttp "GET /l3/bin/10 HTTP/1.1" 500 71143
INFO 25-09-2023 10:42:48 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 10:42:49 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:43:09 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\urls.py changed, reloading.
INFO 25-09-2023 10:43:10 autoreload Watching for file changes with StatReloader
ERROR 25-09-2023 10:44:34 log Internal Server Error: /l3/bin/10
Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: index_wo_templates() got an unexpected keyword argument 'n'
ERROR 25-09-2023 10:44:34 basehttp "GET /l3/bin/10 HTTP/1.1" 500 71143
INFO 25-09-2023 10:45:01 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\urls.py changed, reloading.
INFO 25-09-2023 10:45:02 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:45:03 basehttp "GET /l3/bin/10 HTTP/1.1" 200 3171
INFO 25-09-2023 10:45:03 basehttp "GET /static/myapp/ico/site.webmanifest HTTP/1.1" 304 0
INFO 25-09-2023 10:45:40 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 10:45:41 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:45:42 basehttp "GET /l3/bin/10 HTTP/1.1" 200 3171
INFO 25-09-2023 10:45:42 basehttp "GET /static/myapp/ico/favicon-32x32.png HTTP/1.1" 304 0
INFO 25-09-2023 10:46:06 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 10:46:07 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:46:09 basehttp "GET /l3/bin/10 HTTP/1.1" 200 3171
INFO 25-09-2023 10:47:22 basehttp "GET /l3/bin/10 HTTP/1.1" 200 4474
INFO 25-09-2023 10:47:36 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 10:47:37 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:49:52 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\views.py changed, reloading.
INFO 25-09-2023 10:49:53 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:50:17 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\urls.py changed, reloading.
INFO 25-09-2023 10:50:18 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:50:23 basehttp "GET /l3/dice/10 HTTP/1.1" 200 4388
INFO 25-09-2023 10:51:50 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\urls.py changed, reloading.
INFO 25-09-2023 10:51:51 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 10:51:56 basehttp "GET /l3/rand/10 HTTP/1.1" 200 4456
INFO 25-09-2023 10:52:38 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\myapp\urls.py changed, reloading.
INFO 25-09-2023 10:52:39 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 11:35:41 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 11:36:08 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\urls.py changed, reloading.
INFO 25-09-2023 11:36:09 autoreload Watching for file changes with StatReloader
WARNING 25-09-2023 11:36:19 log Not Found: /l3/authors
WARNING 25-09-2023 11:36:19 basehttp "GET /l3/authors HTTP/1.1" 404 4347
WARNING 25-09-2023 11:36:29 log Not Found: /l3/authors/
WARNING 25-09-2023 11:36:29 basehttp "GET /l3/authors/ HTTP/1.1" 404 4350
INFO 25-09-2023 11:38:23 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\urls.py changed, reloading.
INFO 25-09-2023 11:38:24 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 11:38:26 basehttp "GET /l3/authors/ HTTP/1.1" 200 2892
INFO 25-09-2023 11:38:26 basehttp "GET /static/myapp/ico/site.webmanifest HTTP/1.1" 304 0
INFO 25-09-2023 11:38:52 basehttp "GET /l3/authors/ HTTP/1.1" 200 2901
INFO 25-09-2023 11:38:52 basehttp "GET /static/myapp/ico/favicon-32x32.png HTTP/1.1" 304 0
INFO 25-09-2023 11:39:19 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\views.py changed, reloading.
INFO 25-09-2023 11:39:20 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 11:44:16 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\views.py changed, reloading.
INFO 25-09-2023 11:44:17 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 11:44:49 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\views.py changed, reloading.
INFO 25-09-2023 11:44:50 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 11:46:04 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\models.py changed, reloading.
INFO 25-09-2023 11:46:05 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 11:46:18 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\models.py changed, reloading.
INFO 25-09-2023 11:46:19 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 11:46:30 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\models.py changed, reloading.
INFO 25-09-2023 11:46:31 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 11:47:57 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\urls.py changed, reloading.
INFO 25-09-2023 11:47:58 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 11:48:46 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\urls.py changed, reloading.
INFO 25-09-2023 11:48:47 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 11:50:17 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\views.py changed, reloading.
INFO 25-09-2023 11:50:18 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 11:50:40 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\urls.py changed, reloading.
INFO 25-09-2023 11:50:41 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 11:53:20 basehttp "GET /l3/authors/ HTTP/1.1" 200 2938
ERROR 25-09-2023 11:53:23 log Internal Server Error: /l3/author/8/articles/
Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: author_articles.html, home2app/article_list.html
ERROR 25-09-2023 11:53:23 basehttp "GET /l3/author/8/articles/ HTTP/1.1" 500 92269
INFO 25-09-2023 11:55:11 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\views.py changed, reloading.
INFO 25-09-2023 11:55:12 autoreload Watching for file changes with StatReloader
ERROR 25-09-2023 11:56:29 log Internal Server Error: /l3/author/8/articles/
Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: home2app/author_articles.html, home2app/article_list.html
ERROR 25-09-2023 11:56:29 basehttp "GET /l3/author/8/articles/ HTTP/1.1" 500 92422
INFO 25-09-2023 11:58:57 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\views.py changed, reloading.
INFO 25-09-2023 11:58:58 autoreload Watching for file changes with StatReloader
ERROR 25-09-2023 11:59:06 log Internal Server Error: /l3/author/8/articles/
Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: home2app/author_articles.html, home2app/article_list.html
ERROR 25-09-2023 11:59:06 basehttp "GET /l3/author/8/articles/ HTTP/1.1" 500 92422
ERROR 25-09-2023 12:00:03 log Internal Server Error: /l3/author/8/articles/
Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: home2app/author_articles.html, home2app/article_list.html
ERROR 25-09-2023 12:00:03 basehttp "GET /l3/author/8/articles/ HTTP/1.1" 500 92422
INFO 25-09-2023 12:01:04 basehttp "GET /l3/author/8/articles/ HTTP/1.1" 200 2946
WARNING 25-09-2023 12:01:07 log Not Found: /l3/author/8/articles/article.get_absolute_url
WARNING 25-09-2023 12:01:07 basehttp "GET /l3/author/8/articles/article.get_absolute_url HTTP/1.1" 404 5282
INFO 25-09-2023 12:34:35 basehttp "GET /l3/author/8/articles/ HTTP/1.1" 200 2936
INFO 25-09-2023 12:34:36 basehttp "GET /static/myapp/ico/site.webmanifest HTTP/1.1" 304 0
INFO 25-09-2023 12:34:36 basehttp "GET /static/myapp/ico/favicon-32x32.png HTTP/1.1" 304 0
ERROR 25-09-2023 12:34:38 log Internal Server Error: /l3/article/2/
Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: article_detail.html
ERROR 25-09-2023 12:34:38 basehttp "GET /l3/article/2/ HTTP/1.1" 500 89626
INFO 25-09-2023 12:35:55 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\views.py changed, reloading.
INFO 25-09-2023 12:35:56 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 12:41:38 basehttp "GET /l3/article/2/ HTTP/1.1" 200 3362
INFO 25-09-2023 12:42:09 basehttp "GET /l3/article/2/ HTTP/1.1" 200 3371
INFO 25-09-2023 12:42:50 basehttp "GET /l3/article/2/ HTTP/1.1" 200 3408
INFO 25-09-2023 12:42:51 basehttp "GET /l3/author/8/articles/ HTTP/1.1" 200 2936
INFO 25-09-2023 12:50:43 basehttp "GET /l3/author/8/articles/ HTTP/1.1" 200 3039
INFO 25-09-2023 12:51:03 basehttp "GET /l3/author/8/articles/ HTTP/1.1" 200 3068
INFO 25-09-2023 12:51:04 basehttp "GET /l3/article/3/ HTTP/1.1" 200 3377
INFO 25-09-2023 12:51:31 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\views.py changed, reloading.
INFO 25-09-2023 12:51:32 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 12:53:26 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\views.py changed, reloading.
INFO 25-09-2023 12:53:27 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 12:54:33 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\views.py changed, reloading.
INFO 25-09-2023 12:54:33 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 12:54:36 basehttp "GET /l3/article/3/ HTTP/1.1" 200 3377
INFO 25-09-2023 12:54:37 basehttp "GET /l3/article/3/ HTTP/1.1" 200 3377
INFO 25-09-2023 12:54:37 basehttp "GET /l3/article/3/ HTTP/1.1" 200 3377
INFO 25-09-2023 12:58:13 basehttp "GET /l3/author/8/articles/ HTTP/1.1" 200 3068
INFO 25-09-2023 12:58:17 basehttp "GET /l3/article/3/ HTTP/1.1" 200 3377
INFO 25-09-2023 13:00:28 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\views.py changed, reloading.
INFO 25-09-2023 13:00:29 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 13:30:21 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 13:30:30 basehttp "GET /static/myapp/ico/site.webmanifest HTTP/1.1" 304 0
INFO 25-09-2023 13:30:30 basehttp "GET /static/myapp/ico/favicon-32x32.png HTTP/1.1" 304 0
WARNING 25-09-2023 13:30:36 log Not Found: /l3/author/
WARNING 25-09-2023 13:30:36 basehttp "GET /l3/author/ HTTP/1.1" 404 5177
INFO 25-09-2023 13:30:48 basehttp "GET /l3/authors/ HTTP/1.1" 200 2933
INFO 25-09-2023 13:30:49 basehttp "GET /l3/author/1/articles/ HTTP/1.1" 200 2919
INFO 25-09-2023 13:31:03 basehttp "GET /l3/author/1/articles/ HTTP/1.1" 200 2948
INFO 25-09-2023 13:31:04 basehttp "GET /l3/article/1/ HTTP/1.1" 200 3370
INFO 25-09-2023 13:31:50 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\views.py changed, reloading.
INFO 25-09-2023 13:31:51 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 13:33:38 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\views.py changed, reloading.
INFO 25-09-2023 13:33:39 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 13:43:53 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\views.py changed, reloading.
INFO 25-09-2023 13:43:54 autoreload Watching for file changes with StatReloader
ERROR 25-09-2023 13:43:56 log Internal Server Error: /l3/article/1/
Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\defaulttags.py", line 967, in do_if
    nodelist = parser.parse(("endif",))
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 36: 'endblock', expected 'endif'. Did you forget to register or load this tag?
ERROR 25-09-2023 13:43:56 basehttp "GET /l3/article/1/ HTTP/1.1" 500 191556
INFO 25-09-2023 13:44:50 basehttp "GET /l3/article/1/ HTTP/1.1" 200 3787
INFO 25-09-2023 13:45:03 basehttp "GET /l3/article/1/ HTTP/1.1" 200 3787
INFO 25-09-2023 13:45:16 basehttp "GET /l3/article/1/ HTTP/1.1" 200 3787
INFO 25-09-2023 13:46:04 basehttp "GET /l3/article/1/ HTTP/1.1" 200 3798
INFO 25-09-2023 13:47:29 basehttp "GET /l3/article/1/ HTTP/1.1" 200 4063
INFO 25-09-2023 13:47:58 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2app\views.py changed, reloading.
INFO 25-09-2023 13:47:59 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 13:47:59 basehttp "GET /l3/article/1/ HTTP/1.1" 200 4063
INFO 25-09-2023 13:48:39 basehttp "GET /l3/article/1/ HTTP/1.1" 200 4109
INFO 25-09-2023 13:49:03 basehttp "GET / HTTP/1.1" 200 2802
INFO 25-09-2023 13:49:04 basehttp "GET / HTTP/1.1" 200 2802
INFO 25-09-2023 13:49:10 basehttp "GET /lesson1/ HTTP/1.1" 200 3369
INFO 25-09-2023 13:59:13 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\models.py changed, reloading.
INFO 25-09-2023 13:59:14 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 14:09:21 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\views.py changed, reloading.
INFO 25-09-2023 14:09:22 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 14:15:44 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\models.py changed, reloading.
INFO 25-09-2023 14:15:45 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 14:18:48 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\urls.py changed, reloading.
INFO 25-09-2023 14:18:49 autoreload Watching for file changes with StatReloader
WARNING 25-09-2023 14:19:00 log Not Found: /l3/orders/
WARNING 25-09-2023 14:19:00 basehttp "GET /l3/orders/ HTTP/1.1" 404 5177
WARNING 25-09-2023 14:19:26 log Not Found: /h2sop/l3/orders/
WARNING 25-09-2023 14:19:26 basehttp "GET /h2sop/l3/orders/ HTTP/1.1" 404 5195
WARNING 25-09-2023 14:19:53 log Not Found: /h2sop/
WARNING 25-09-2023 14:19:53 basehttp "GET /h2sop/ HTTP/1.1" 404 5165
INFO 25-09-2023 14:20:03 basehttp "GET /h2shop/ HTTP/1.1" 200 47
WARNING 25-09-2023 14:20:11 log Not Found: /h2shop/order
WARNING 25-09-2023 14:20:11 basehttp "GET /h2shop/order HTTP/1.1" 404 5800
WARNING 25-09-2023 14:20:17 log Not Found: /h2shop/orders
WARNING 25-09-2023 14:20:17 basehttp "GET /h2shop/orders HTTP/1.1" 404 5803
INFO 25-09-2023 14:20:31 basehttp "GET /h2shop/l3/orders HTTP/1.1" 301 0
INFO 25-09-2023 14:20:31 basehttp "GET /h2shop/l3/orders/ HTTP/1.1" 200 2813
INFO 25-09-2023 14:20:31 basehttp "GET /static/myapp/ico/site.webmanifest HTTP/1.1" 304 0
INFO 25-09-2023 14:30:15 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\models.py changed, reloading.
INFO 25-09-2023 14:30:16 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 14:30:46 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\models.py changed, reloading.
INFO 25-09-2023 14:30:47 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 14:39:27 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\models.py changed, reloading.
INFO 25-09-2023 14:39:28 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 14:46:01 basehttp "GET /h2shop/l3/orders/ HTTP/1.1" 200 2917
INFO 25-09-2023 14:46:02 basehttp "GET /static/myapp/ico/favicon-32x32.png HTTP/1.1" 304 0
INFO 25-09-2023 14:46:30 basehttp "GET /h2shop/l3/orders/ HTTP/1.1" 200 2917
INFO 25-09-2023 14:46:31 basehttp "GET /h2shop/l3/orders/ HTTP/1.1" 200 2917
INFO 25-09-2023 14:47:05 basehttp "GET /h2shop/l3/orders/ HTTP/1.1" 200 2927
INFO 25-09-2023 14:47:20 basehttp "GET /h2shop/l3/orders/ HTTP/1.1" 200 2927
INFO 25-09-2023 14:47:21 basehttp "GET /h2shop/l3/orders/ HTTP/1.1" 200 2930
INFO 25-09-2023 14:49:12 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\models.py changed, reloading.
INFO 25-09-2023 14:49:13 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 14:49:13 basehttp "GET /h2shop/l3/orders/ HTTP/1.1" 200 3015
INFO 25-09-2023 14:49:51 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\models.py changed, reloading.
INFO 25-09-2023 14:49:53 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 14:49:53 basehttp "GET /h2shop/l3/orders/ HTTP/1.1" 200 3051
INFO 25-09-2023 14:50:07 basehttp "GET /h2shop/l3/orders/ HTTP/1.1" 200 3055
INFO 25-09-2023 14:50:25 basehttp "GET /h2shop/l3/orders/ HTTP/1.1" 200 3055
INFO 25-09-2023 14:50:26 basehttp "GET /h2shop/l3/orders/ HTTP/1.1" 200 3057
INFO 25-09-2023 14:51:09 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\models.py changed, reloading.
INFO 25-09-2023 14:51:10 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 15:01:42 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\urls.py changed, reloading.
INFO 25-09-2023 15:01:43 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 15:02:53 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\views.py changed, reloading.
INFO 25-09-2023 15:02:54 autoreload Watching for file changes with StatReloader
ERROR 25-09-2023 15:03:02 log Internal Server Error: /h2shop/l3/order/1
Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\views\generic\detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
  File "C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\views.py", line 75, in get_context_data
    context['products'] = Product.objects.filter(order_id=pk)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'order_id' into field. Choices are: art, creation_date, description, id, is_visible, modified_date, order, orderproduct, qty, title, unit_price
ERROR 25-09-2023 15:03:02 basehttp "GET /h2shop/l3/order/1 HTTP/1.1" 500 132501
INFO 25-09-2023 15:03:28 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\views.py changed, reloading.
INFO 25-09-2023 15:03:29 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 15:03:30 basehttp "GET /h2shop/l3/order/1 HTTP/1.1" 200 3254
INFO 25-09-2023 15:05:49 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\views.py changed, reloading.
INFO 25-09-2023 15:05:50 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 15:05:51 basehttp "GET /h2shop/l3/order/1 HTTP/1.1" 200 3478
INFO 25-09-2023 15:08:10 basehttp "GET /h2shop/l3/order/1 HTTP/1.1" 200 3750
INFO 25-09-2023 15:08:10 basehttp "GET /static/myapp/ico/site.webmanifest HTTP/1.1" 304 0
INFO 25-09-2023 15:08:36 basehttp "GET /h2shop/l3/order/1 HTTP/1.1" 200 3754
INFO 25-09-2023 15:09:04 basehttp "GET /h2shop/l3/order/1 HTTP/1.1" 200 3786
INFO 25-09-2023 15:18:50 basehttp "GET /h2shop/l3/order/1 HTTP/1.1" 200 4242
INFO 25-09-2023 15:19:14 basehttp "GET /h2shop/l3/order/1 HTTP/1.1" 200 4254
INFO 25-09-2023 15:20:26 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\views.py changed, reloading.
INFO 25-09-2023 15:20:27 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 15:20:49 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\models.py changed, reloading.
INFO 25-09-2023 15:20:50 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 15:25:09 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\urls.py changed, reloading.
INFO 25-09-2023 15:25:10 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 15:25:29 basehttp "GET /h2shop/l3/orders/1 HTTP/1.1" 200 3025
INFO 25-09-2023 15:25:35 basehttp "GET /h2shop/l3/orders/2 HTTP/1.1" 200 2789
INFO 25-09-2023 15:25:38 basehttp "GET /h2shop/l3/orders/1 HTTP/1.1" 200 3025
INFO 25-09-2023 15:36:57 basehttp "GET /h2shop/l3/orders/1 HTTP/1.1" 200 3025
INFO 25-09-2023 15:36:57 basehttp "GET /static/myapp/ico/favicon-32x32.png HTTP/1.1" 304 0
INFO 25-09-2023 15:39:11 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\urls.py changed, reloading.
INFO 25-09-2023 15:39:12 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 15:39:13 basehttp "GET /h2shop/l3/orders/1 HTTP/1.1" 200 3042
INFO 25-09-2023 15:39:17 basehttp "GET /h2shop/l3/order/1 HTTP/1.1" 200 4254
INFO 25-09-2023 15:42:22 basehttp "GET /h2shop/l3/orders/1 HTTP/1.1" 200 3042
INFO 25-09-2023 15:42:23 basehttp "GET /h2shop/l3/order/1 HTTP/1.1" 200 4254
INFO 25-09-2023 16:05:52 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\views.py changed, reloading.
INFO 25-09-2023 16:05:54 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 16:07:31 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\views.py changed, reloading.
INFO 25-09-2023 16:07:32 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 16:07:43 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\views.py changed, reloading.
INFO 25-09-2023 16:07:44 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 16:08:04 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\views.py changed, reloading.
INFO 25-09-2023 16:08:05 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 16:12:24 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\views.py changed, reloading.
INFO 25-09-2023 16:12:25 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 16:13:04 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\views.py changed, reloading.
INFO 25-09-2023 16:13:05 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 16:14:14 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\views.py changed, reloading.
INFO 25-09-2023 16:14:15 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 16:18:48 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\views.py changed, reloading.
INFO 25-09-2023 16:18:50 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 16:19:38 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 16:19:59 autoreload Watching for file changes with StatReloader
WARNING 25-09-2023 16:20:34 log Not Found: /h2shop/l3/products/1/
WARNING 25-09-2023 16:20:34 basehttp "GET /h2shop/l3/products/1/ HTTP/1.1" 404 6451
ERROR 25-09-2023 16:20:39 log Internal Server Error: /h2shop/l3/products/1/sfdg
Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: your_template.html, home2shopapp/orderproduct_list.html
ERROR 25-09-2023 16:20:39 basehttp "GET /h2shop/l3/products/1/sfdg HTTP/1.1" 500 93136
INFO 25-09-2023 16:21:13 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\views.py changed, reloading.
INFO 25-09-2023 16:21:14 autoreload Watching for file changes with StatReloader
ERROR 25-09-2023 16:21:17 log Internal Server Error: /h2shop/l3/products/1/sfdg
Traceback (most recent call last):
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\template\defaulttags.py", line 320, in render
    if match:
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\db\models\query.py", line 412, in __bool__
    self._fetch_all()
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 785, in as_sql
    distinct_result, distinct_params = self.connection.ops.distinct_sql(
  File "C:\Users\Andre\PycharmProjects\gb_django\venv\lib\site-packages\django\db\backends\base\operations.py", line 202, in distinct_sql
    raise NotSupportedError(
django.db.utils.NotSupportedError: DISTINCT ON fields is not supported by this database backend
ERROR 25-09-2023 16:21:17 basehttp "GET /h2shop/l3/products/1/sfdg HTTP/1.1" 500 179331
INFO 25-09-2023 16:25:12 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\views.py changed, reloading.
INFO 25-09-2023 16:25:13 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 16:25:19 basehttp "GET /h2shop/l3/products/1/sfdg HTTP/1.1" 200 3777
INFO 25-09-2023 16:25:19 basehttp "GET /static/myapp/ico/site.webmanifest HTTP/1.1" 304 0
INFO 25-09-2023 16:27:29 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\views.py changed, reloading.
INFO 25-09-2023 16:27:30 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 16:27:30 basehttp "GET /h2shop/l3/products/1/sfdg HTTP/1.1" 200 3777
INFO 25-09-2023 16:30:15 autoreload C:\Users\Andre\PycharmProjects\gb_django\home\home2shopapp\views.py changed, reloading.
INFO 25-09-2023 16:30:16 autoreload Watching for file changes with StatReloader
INFO 25-09-2023 16:30:18 basehttp "GET /h2shop/l3/products/1/sfdg HTTP/1.1" 200 3777
INFO 25-09-2023 16:30:56 basehttp "GET /h2shop/l3/products/1/sfdg HTTP/1.1" 200 2917
INFO 25-09-2023 16:30:56 basehttp "GET /static/myapp/ico/favicon-32x32.png HTTP/1.1" 304 0
